"""add_national_holiday

Revision ID: 278a2cde6682
Revises: 1f01cd9839a1
Create Date: 2026-03-30 14:13:48.980355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '278a2cde6682'
down_revision: Union[str, Sequence[str], None] = '1f01cd9839a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationalholiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nationalholiday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nationalholiday_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nationalholiday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nationalholiday_date'))

    op.drop_table('nationalholiday')
    # ### end Alembic commands ###
