"""fix_sign_loop

Revision ID: 4adfd3eb527f
Revises: 7604314f290e
Create Date: 2026-03-31 10:37:25.071479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4adfd3eb527f'
down_revision: Union[str, Sequence[str], None] = '7604314f290e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_auto_in_1', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_auto_out_1', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_auto_in_2', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_auto_out_2', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_auto_out_2')
        batch_op.drop_column('last_auto_in_2')
        batch_op.drop_column('last_auto_out_1')
        batch_op.drop_column('last_auto_in_1')

    # ### end Alembic commands ###
