"""add_automation_fields

Revision ID: 7604314f290e
Revises: 278a2cde6682
Create Date: 2026-03-31 10:19:04.212357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7604314f290e'
down_revision: Union[str, Sequence[str], None] = '278a2cde6682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('margin_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_checking_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('today_offset_in_1', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('today_offset_out_1', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('today_offset_in_2', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('today_offset_out_2', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('last_offset_date', sa.Date(), nullable=True))
        batch_op.alter_column('rol',
               nullable=False,
               existing_server_default=sa.text("'user'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rol',
               nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.drop_column('last_offset_date')
        batch_op.drop_column('today_offset_out_2')
        batch_op.drop_column('today_offset_in_2')
        batch_op.drop_column('today_offset_out_1')
        batch_op.drop_column('today_offset_in_1')
        batch_op.drop_column('active_checking_id')

    op.drop_table('globalsettings')
    # ### end Alembic commands ###
